/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_thefirendkdemo_MainActivity */

#ifndef _Included_com_example_thefirendkdemo_MainActivity
#define _Included_com_example_thefirendkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_thefirendkdemo_MainActivity
 * Method:    getStringFromActivity
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_thefirendkdemo_MainActivity_getStringFromActivity
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
